# Generated by Django 2.2.6 on 2019-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreational', '0010_auto_20191110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.URLField(),
        ),
    ]
