# Generated by Django 2.2.6 on 2019-11-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0007_auto_20191112_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='memeber1',
            new_name='member1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memeber2',
            new_name='member2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memeber3',
            new_name='member3',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memeber4',
            new_name='member4',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memeber5',
            new_name='member5',
        ),
    ]
