# Generated by Django 2.2.6 on 2019-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0008_auto_20191112_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='member2',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='member3',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='member4',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='member5',
            field=models.CharField(max_length=256),
        ),
    ]
