# Generated by Django 2.2.6 on 2019-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Topic', models.CharField(max_length=264)),
                ('Place', models.CharField(max_length=264)),
                ('Date', models.DateField()),
                ('Objec', models.TextField()),
            ],
        ),
    ]
