# Generated by Django 2.2.6 on 2019-11-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0002_auto_20191111_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='topic',
            field=models.CharField(max_length=264),
        ),
    ]
