# Generated by Django 2.2.6 on 2019-11-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0004_auto_20191112_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venture',
            old_name='m1',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='m4',
        ),
    ]
