# Generated by Django 2.2.6 on 2019-11-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_userprofileinfo_skill'),
        ('Meeting', '0005_auto_20191112_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('deadline', models.DateField()),
                ('memebername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.UserProfileInfo')),
            ],
        ),
    ]
