# Generated by Django 2.2.6 on 2019-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='memebername',
        ),
        migrations.AddField(
            model_name='project',
            name='memeber1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='memeber2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='memeber3',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='memeber4',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='memeber5',
            field=models.CharField(default='', max_length=256),
        ),
    ]
