# Generated by Django 2.2.6 on 2019-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0009_auto_20191112_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='idd',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
