# Generated by Django 2.2.6 on 2019-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exampuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
