# Generated by Django 2.2.6 on 2019-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20191108_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='skill',
            field=models.TextField(default=''),
        ),
    ]
