# Generated by Django 2.2.6 on 2019-11-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreational', '0005_auto_20191110_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='static/img/recreation_menu_data'),
        ),
    ]
