# Generated by Django 2.2.6 on 2019-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=264)),
                ('LastName', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
